### PR TITLE
Move from Docusaurus to Nextra

### PR DESCRIPTION
**Pull request by pcho**
New documentation site based on Nextra 2.0.

### CODE REVIEW

**Comment by pcho** [comment]
Here’s a preview: https://bd-ebon.vercel.app/

**Comment by yury** [comment]
Hello @pcho!

I did merge some pull-requests from contributes before. Please fix conflicts and we are good to merge and move to Nextra!

**Comment by yury** [comment]
Also, https://github.com/blinksh/docs#readme is outdated after this PR

**Comment by pcho** [comment]
> Also, https://github.com/blinksh/docs#readme is outdated after this PR

I updated everything + newest nextra and theme. :)

**Comment by yury** [comment]
Thank you!

**Comment by pcho** [comment]
> Thank you!

n/p, but it doesn’t seem to be online? Do you need anything else?

**Comment by yury** [comment]
Not yet, yep. Will deploy this week.

**Pull request merged**
